[package]
name = "autowp2mp4"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24.9"
tokio = { version = "1.43.0", features = ["full"] }
webp = "0.2.0"
webp-animation = { version = "0.9.0", features = ["image","static"] }
